# .github/release.toml

[workflow]
manual_approval = true

[validate]
steps = ["validate-python.sh"]

[build]
steps = ["build-python.sh"]
final_validation_step = "validate-python.sh"

[assets]
source_directory = "dist/"
include = ["*"]
exclude = []

[changelog]
template = """
### What's Changed in ${REPO_NAME} ${TAG}

${COMMITS}

**Full Changelog**: ${URL}
"""
